// Code generated by src/herdr/generate-types.ts from `herdr api schema --json`.
// DO NOT EDIT. Protocol 20, schema version 1.

export namespace HerdrParams {
  export interface AgentPromptParams { target: string; text: string; wait?: HerdrParams.AgentPromptWaitOptions | null; }
  export interface AgentPromptWaitOptions { timeout_ms?: number | null; until?: HerdrParams.AgentStatus[]; }
  export interface AgentReadParams { format?: HerdrParams.ReadFormat; lines?: number | null; source: HerdrParams.ReadSource; strip_ansi?: boolean; target: string; }
  export interface AgentStartParams { args?: string[]; kind: string; name: string; pane_id: string; /** Startup timeout in milliseconds. Values must be greater than 3000 and at most 300000. */ timeout_ms?: number | null; }
  export type AgentStatus = "idle" | "working" | "blocked" | "done" | "unknown";
  export type EmptyParams = Record<string, unknown>;
  export interface EventsSubscribeParams { subscriptions: HerdrParams.Subscription[]; }
  export type OutputMatch = { type: "substring"; value: string; } | { type: "regex"; value: string; };
  export interface PaneReadParams { format?: HerdrParams.ReadFormat; lines?: number | null; pane_id: string; source: HerdrParams.ReadSource; strip_ansi?: boolean; }
  export interface PaneSendInputParams { keys?: string[]; pane_id: string; text?: string; }
  export interface PaneSendKeysParams { keys: string[]; pane_id: string; }
  export type PingParams = Record<string, unknown>;
  export type ReadFormat = "text" | "ansi";
  export type ReadSource = "visible" | "recent" | "recent_unwrapped" | "detection";
  export type Subscription = { type: "workspace.created"; } | { type: "workspace.updated"; } | { type: "workspace.metadata_updated"; } | { type: "workspace.renamed"; } | { type: "workspace.moved"; } | { type: "workspace.reordered"; } | { type: "workspace.closed"; } | { type: "workspace.focused"; } | { type: "worktree.created"; } | { type: "worktree.opened"; } | { type: "worktree.removed"; } | { type: "tab.created"; } | { type: "tab.closed"; } | { type: "tab.focused"; } | { type: "tab.renamed"; } | { type: "tab.moved"; } | { type: "pane.created"; } | { type: "pane.closed"; } | { type: "pane.updated"; } | { type: "pane.focused"; } | { type: "pane.moved"; } | { type: "pane.exited"; } | { type: "pane.agent_detected"; } | { lines?: number | null; match: HerdrParams.OutputMatch; pane_id: string; source: HerdrParams.ReadSource; strip_ansi?: boolean; type: "pane.output_matched"; } | { agent_status?: HerdrParams.AgentStatus | null; pane_id: string; type: "pane.agent_status_changed"; } | { pane_id: string; type: "pane.scroll_changed"; } | { type: "layout.updated"; };
  export interface WorkspaceCreateParams { cwd?: string | null; env?: Record<string, string>; focus?: boolean; label?: string | null; }
  export interface WorkspaceReportMetadataParams { seq?: number | null; source: string; tokens: Record<string, string | null>; ttl_ms?: number | null; workspace_id: string; }
}

export namespace HerdrResults {
  export interface AgentPrompted { agent: HerdrResults.AgentInfo; type: "agent_prompted"; }
  export interface AgentStarted { agent: HerdrResults.AgentInfo; argv: string[]; type: "agent_started"; }
  export interface Ok { type: "ok"; }
  export interface PaneRead { read: HerdrResults.PaneReadResult; type: "pane_read"; }
  export interface Pong { capabilities?: HerdrResults.ServerCapabilities | null; protocol: number; type: "pong"; version: string; }
  export interface SessionSnapshot { snapshot: HerdrResults.SessionSnapshot; type: "session_snapshot"; }
  export interface SubscriptionStarted { type: "subscription_started"; }
  export interface WorkspaceCreated { root_pane: HerdrResults.PaneInfo; tab: HerdrResults.TabInfo; type: "workspace_created"; workspace: HerdrResults.WorkspaceInfo; }
  export interface AgentInfo { agent?: string | null; agent_session?: HerdrResults.AgentSessionInfo | null; agent_status: HerdrResults.AgentStatus; cwd?: string | null; display_agent?: string | null; focused: boolean; foreground_cwd?: string | null; interactive_ready?: boolean; launch_pending?: boolean; name?: string | null; pane_id: string; revision: number; screen_detection_skipped?: boolean; state_change_seq?: number; state_labels?: Record<string, string>; tab_id: string; terminal_id: string; terminal_title?: string | null; terminal_title_stripped?: string | null; title?: string | null; tokens?: Record<string, string>; workspace_id: string; }
  export interface AgentSessionInfo { agent: string; kind: HerdrResults.AgentSessionRefKind; source: string; value: string; }
  export type AgentSessionRefKind = "id" | "path";
  export type AgentStatus = "idle" | "working" | "blocked" | "done" | "unknown";
  export interface PaneInfo { agent?: string | null; agent_session?: HerdrResults.AgentSessionInfo | null; agent_status: HerdrResults.AgentStatus; cwd?: string | null; display_agent?: string | null; focused: boolean; foreground_cwd?: string | null; label?: string | null; pane_id: string; revision: number; scroll?: HerdrResults.PaneScrollInfo | null; state_labels?: Record<string, string>; tab_id: string; terminal_id: string; terminal_title?: string | null; terminal_title_stripped?: string | null; title?: string | null; tokens?: Record<string, string>; workspace_id: string; }
  export interface PaneLayoutPane { focused: boolean; pane_id: string; rect: HerdrResults.PaneLayoutRect; }
  export interface PaneLayoutRect { height: number; width: number; x: number; y: number; }
  export interface PaneLayoutSnapshot { area: HerdrResults.PaneLayoutRect; focused_pane_id: string; panes: HerdrResults.PaneLayoutPane[]; splits: HerdrResults.PaneLayoutSplit[]; tab_id: string; workspace_id: string; zoomed: boolean; }
  export interface PaneLayoutSplit { direction: HerdrResults.SplitDirection; id: string; ratio: number; rect: HerdrResults.PaneLayoutRect; }
  export interface PaneReadResult { format: HerdrResults.ReadFormat; pane_id: string; revision: number; source: HerdrResults.ReadSource; tab_id: string; text: string; truncated: boolean; workspace_id: string; }
  export interface PaneScrollInfo { max_offset_from_bottom: number; offset_from_bottom: number; viewport_rows: number; }
  export type ReadFormat = "text" | "ansi";
  export type ReadSource = "visible" | "recent" | "recent_unwrapped" | "detection";
  export interface ServerCapabilities { detached_server_daemon?: boolean; live_handoff: boolean; }
  export interface SessionSnapshot { agents: HerdrResults.AgentInfo[]; focused_pane_id?: string | null; focused_tab_id?: string | null; focused_workspace_id?: string | null; layouts: HerdrResults.PaneLayoutSnapshot[]; panes: HerdrResults.PaneInfo[]; protocol: number; tabs: HerdrResults.TabInfo[]; version: string; workspaces: HerdrResults.WorkspaceInfo[]; }
  export type SplitDirection = "right" | "down";
  export interface TabInfo { agent_status: HerdrResults.AgentStatus; focused: boolean; label: string; number: number; pane_count: number; tab_id: string; workspace_id: string; }
  export interface WorkspaceInfo { active_tab_id: string; agent_status: HerdrResults.AgentStatus; focused: boolean; label: string; number: number; pane_count: number; tab_count: number; tokens?: Record<string, string>; workspace_id: string; worktree?: HerdrResults.WorkspaceWorktreeInfo | null; }
  export interface WorkspaceWorktreeInfo { checkout_path: string; is_linked_worktree: boolean; repo_key: string; repo_name: string; repo_root: string; }
}

/** Methods covered by the generated table, with their params and result payloads. */
export interface HerdrMethodTable {
  "ping": { params: HerdrParams.PingParams; result: HerdrResults.Pong; };
  "session.snapshot": { params: HerdrParams.EmptyParams; result: HerdrResults.SessionSnapshot; };
  "workspace.create": { params: HerdrParams.WorkspaceCreateParams; result: HerdrResults.WorkspaceCreated; };
  "workspace.report_metadata": { params: HerdrParams.WorkspaceReportMetadataParams; result: HerdrResults.Ok; };
  "agent.start": { params: HerdrParams.AgentStartParams; result: HerdrResults.AgentStarted; };
  "agent.prompt": { params: HerdrParams.AgentPromptParams; result: HerdrResults.AgentPrompted; };
  "agent.read": { params: HerdrParams.AgentReadParams; result: HerdrResults.PaneRead; };
  "pane.read": { params: HerdrParams.PaneReadParams; result: HerdrResults.PaneRead; };
  "pane.send_input": { params: HerdrParams.PaneSendInputParams; result: HerdrResults.Ok; };
  "pane.send_keys": { params: HerdrParams.PaneSendKeysParams; result: HerdrResults.Ok; };
  "events.subscribe": { params: HerdrParams.EventsSubscribeParams; result: HerdrResults.SubscriptionStarted; };
}

export type HerdrMethod = keyof HerdrMethodTable;

/** Success envelope: every response with an `id` carries one of these. */
export interface HerdrSuccessResponse {
  id: string;
  result: HerdrMethodTable[HerdrMethod]["result"];
}

/** Error envelope. Malformed requests are answered with an empty `id`. */
export interface HerdrErrorBody { code: string; message: string; }
export interface HerdrErrorResponse {
  id: string;
  error: HerdrErrorBody;
}

/** Dotted subscription kinds accepted by `events.subscribe` (from the schema). */
export type HerdrSubscriptionEventKind = "pane.output_matched" | "pane.agent_status_changed" | "pane.scroll_changed";
/** Underscored broadcast event kinds (from the schema). */
export type HerdrEventKind = "workspace_created" | "workspace_updated" | "workspace_metadata_updated" | "workspace_closed" | "workspace_renamed" | "workspace_moved" | "workspace_reordered" | "workspace_focused" | "worktree_created" | "worktree_opened" | "worktree_removed" | "tab_created" | "tab_closed" | "tab_renamed" | "tab_moved" | "tab_focused" | "pane_created" | "pane_closed" | "pane_updated" | "pane_focused" | "pane_moved" | "pane_output_changed" | "pane_exited" | "pane_agent_detected" | "pane_agent_status_changed" | "layout_updated";
/**
 * One streamed frame on a subscribed connection. Narrow `data` by `event`.
 * `pane.agent_status_changed` (the ticket's acceptance event) carries
 * `{ pane_id, workspace_id, agent_status }` plus nullable agent/title fields.
 */
export interface HerdrStreamEvent {
  event: string;
  data: unknown;
}

